downloadDir: "/blue/weishao/normansmith/data"
allScenesOutputDir: "/blue/weishao/normansmith/data/shards/all_scenes"
allSuccessOutputDir: /blue/weishao/normansmith/data/shards/success_only

numWorkers: 10

monteCarloRewards:
  discountFactor: 0.99
  terminalReward: 1.0



